version: "3"
services:
  db:
    image: postgres:14
    container_name: copsbootdb
    environment:
      - POSTGRES_USER=copsbootdb
      - POSTGRES_PASSWORD=my-postgres-db-pwd
      - POSTGRES_DB=copsbootdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: